### ISSUE TITLE
Enable sadc - System activity data collector

### ISSUE THREAD

**Issue by venkivijay** [venkivijay/infra#8]
sadc needs to be enabled to collect system activities. 

```yaml
- name: Ensure sadc is enabled
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED="true"
 ```
